name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  flutter_offline_sync:
    path: ../
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  built_value: ^8.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 
  objectbox_generator: ^4.3.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  built_value_generator: ^8.9.2

flutter:
  uses-material-design: true
