name: flutter_offline_sync
description: "A package to sync data between dart and the remote server"
publish_to: 'none'
version: 0.1.0
repository: https://github.com/MuhammedKasujja/flutter-offline-sync

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  logger: ^2.5.0
  objectbox: ^4.2.0
  objectbox_flutter_libs: ^4.2.0
  path_provider: ^2.1.5
  freezed_annotation: ^3.0.0
  path: ^1.9.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  objectbox_generator: ^4.2.0
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
